# Generated by Django 5.1.7 on 2025-03-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apply_course_product_coursesection_lesson_purchase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='price_paid_in_cents',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
