# Generated by Django 5.1.7 on 2025-05-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_employee_name_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='candidateId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='candidates', to='api.candidates'),
        ),
        migrations.AddField(
            model_name='employee',
            name='departmentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employees', to='api.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
