name: Deploy Django Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Copy files to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ssh root@148.230.120.114 "
            cd /opt/techvision_backend &&
            git pull &&
            docker-compose build &&
            docker-compose up -d --remove-orphans
          "
